### PR TITLE
ADD: Sound system/character manager

### LINKED ISSUE #96: Character Sound Manager
This Component will handle all triggers related to a character. This can be the player but also all kind of NPCs.

### PR DESCRIPTION
**Pull request by Segelzwerg**
This adds a sound manager for all characters.

Know Bugs: 
- [x] sounds continues to be played in menu found by @Thabb done by 1f2d205

All sounds used are licensed with [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

closes #96

### CODE REVIEW

**Review by Thabb — CHANGES_REQUESTED** [review]
Issues I found:
- The sound keeps playing while in Air.
- There is sound for walking, running and walking & sneaking, but not for running & sneaking

**Comment by Segelzwerg** [comment]
> Issues I found:
> 
> * The sound keeps playing while in Air.
> * There is sound for walking, running and walking & sneaking, but not for running & sneaking

Running & sneaking we discuss to use the running sound.

But, @Thabb , I cannot reproducing playing sound while airborne. Can you check newest push?

**Comment by Segelzwerg** [comment]
@Thabb how do you feel about the public fields of sound clips? In near future they could be hundreds depending all the different terrain and object the character could walk/run/sneak on. I feel like this should move to a wrapper class. What is your opinion on this?

**Comment by Segelzwerg** [comment]
I think this can go to production. We could think of more triggers we need, but I would suggest we implement them as we need them as most of them would be copy & paste.

**Review by Thabb — APPROVED** [review]

**Pull request merged**
