### PR TITLE
ADD: Interactable to take an item and drag it around

### PR DESCRIPTION
**Pull request by Thabb**

### CODE REVIEW

**Comment by iTitus** [comment]
The `improvementsVersion` branches don't seem to have the newest `master` changes in them. Shall I attempt a merge?

**Comment by Thabb** [comment]
You can do that. It won't hurt.

**Comment by iTitus** [comment]
This is a nice idea and kinda works but it still has its quirks.
Foe example you cannot really lift the object up, as mouse movement up/down doesn't do anything...

**Review by iTitus — APPROVED** [review]

**Comment by Thabb** [comment]
True. I had this changed already, but seems like i forgot to commit it. Will fix it.

**Review by iTitus — CHANGES_REQUESTED** [review]
Doesn't work with the SoundAreas. The item drops and cannot be picked back up when walking into one.

**Comment by Thabb** [comment]
Fixed, pls recheck

**Pull request merged**
